# Spring boot application
spring:
  application:
    name: hello-dubbo-service-user-consumer

server:
  port: 9090

# UserService service version
user:
  service:
    version: 1.0.0


dubbo:
  scan:
    basePackages: com.juntao.hello.dubbo.service.user.consumer.controller
  application:
    id: hello-dubbo-service-user-consumer
    name: hello-dubbo-service-user-consumer
    ## RegistryConfig Bean
  registry:
    id: zookeeper
    address: zookeeper://192.168.95.131:2181?backup=192.168.95.131:2182,192.168.95.131:2183
  protocol:
    serialization: kryo


# Dubbo Endpoint (default status is disable)
endpoints:
  dubbo:
    enabled: true

